name: "Setup Node and Install"
description: "Reusable action to setup node and install dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
      shell: bash
